/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterFormRouteImport } from './routes/register/form'
import { Route as RegisterFormIndexRouteImport } from './routes/register/form/index'
import { Route as RegisterFormIndividualRouteImport } from './routes/register/form/individual'
import { Route as RegisterFormSchoolRouteImport } from './routes/register/form/school'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterFormRoute = RegisterFormRouteImport.update({
  id: '/register/form',
  path: '/register/form',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterFormIndexRoute = RegisterFormIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterFormRoute,
} as any)
const RegisterFormIndividualRoute = RegisterFormIndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => RegisterFormRoute,
} as any)
const RegisterFormSchoolRoute = RegisterFormSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => RegisterFormRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/register/form': typeof RegisterFormRouteWithChildren
  '/register/': typeof RegisterIndexRoute
  '/register/form/individual': typeof RegisterFormIndividualRoute
  '/register/form/school': typeof RegisterFormSchoolRoute
  '/register/form/': typeof RegisterFormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/register': typeof RegisterIndexRoute
  '/register/form/individual': typeof RegisterFormIndividualRoute
  '/register/form/school': typeof RegisterFormSchoolRoute
  '/register/form': typeof RegisterFormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/register/form': typeof RegisterFormRouteWithChildren
  '/register/': typeof RegisterIndexRoute
  '/register/form/individual': typeof RegisterFormIndividualRoute
  '/register/form/school': typeof RegisterFormSchoolRoute
  '/register/form/': typeof RegisterFormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/faq'
    | '/resources'
    | '/team'
    | '/register/form'
    | '/register/'
    | '/register/form/individual'
    | '/register/form/school'
    | '/register/form/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/faq'
    | '/resources'
    | '/team'
    | '/register'
    | '/register/form/individual'
    | '/register/form/school'
    | '/register/form'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/faq'
    | '/resources'
    | '/team'
    | '/register/form'
    | '/register/'
    | '/register/form/individual'
    | '/register/form/school'
    | '/register/form/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamRoute: typeof TeamRoute
  RegisterFormRoute: typeof RegisterFormRouteWithChildren
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/form': {
      id: '/register/form'
      path: '/register/form'
      fullPath: '/register/form'
      preLoaderRoute: typeof RegisterFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/form/': {
      id: '/register/form/'
      path: '/'
      fullPath: '/register/form/'
      preLoaderRoute: typeof RegisterFormIndexRouteImport
      parentRoute: typeof RegisterFormRoute
    }
    '/register/form/individual': {
      id: '/register/form/individual'
      path: '/individual'
      fullPath: '/register/form/individual'
      preLoaderRoute: typeof RegisterFormIndividualRouteImport
      parentRoute: typeof RegisterFormRoute
    }
    '/register/form/school': {
      id: '/register/form/school'
      path: '/school'
      fullPath: '/register/form/school'
      preLoaderRoute: typeof RegisterFormSchoolRouteImport
      parentRoute: typeof RegisterFormRoute
    }
  }
}

interface RegisterFormRouteChildren {
  RegisterFormIndividualRoute: typeof RegisterFormIndividualRoute
  RegisterFormSchoolRoute: typeof RegisterFormSchoolRoute
  RegisterFormIndexRoute: typeof RegisterFormIndexRoute
}

const RegisterFormRouteChildren: RegisterFormRouteChildren = {
  RegisterFormIndividualRoute: RegisterFormIndividualRoute,
  RegisterFormSchoolRoute: RegisterFormSchoolRoute,
  RegisterFormIndexRoute: RegisterFormIndexRoute,
}

const RegisterFormRouteWithChildren = RegisterFormRoute._addFileChildren(
  RegisterFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  ResourcesRoute: ResourcesRoute,
  TeamRoute: TeamRoute,
  RegisterFormRoute: RegisterFormRouteWithChildren,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
