/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesRouteImport } from './routes/_resources'
import { Route as EventsRouteImport } from './routes/events'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResourcesAboutRouteImport } from './routes/_resources/about'
import { Route as ResourcesContactRouteImport } from './routes/_resources/contact'
import { Route as ResourcesFaqRouteImport } from './routes/_resources/faq'
import { Route as ResourcesResourcesRouteImport } from './routes/_resources/resources'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterFormRouteImport } from './routes/register/form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/_resources',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesAboutRoute = ResourcesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesContactRoute = ResourcesContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesFaqRoute = ResourcesFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesResourcesRoute = ResourcesResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ResourcesRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterFormRoute = RegisterFormRouteImport.update({
  id: '/register/form',
  path: '/register/form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/team': typeof TeamRoute
  '/about': typeof ResourcesAboutRoute
  '/contact': typeof ResourcesContactRoute
  '/faq': typeof ResourcesFaqRoute
  '/resources': typeof ResourcesResourcesRoute
  '/register/form': typeof RegisterFormRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/team': typeof TeamRoute
  '/about': typeof ResourcesAboutRoute
  '/contact': typeof ResourcesContactRoute
  '/faq': typeof ResourcesFaqRoute
  '/resources': typeof ResourcesResourcesRoute
  '/register/form': typeof RegisterFormRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_resources': typeof ResourcesRouteWithChildren
  '/events': typeof EventsRoute
  '/team': typeof TeamRoute
  '/_resources/about': typeof ResourcesAboutRoute
  '/_resources/contact': typeof ResourcesContactRoute
  '/_resources/faq': typeof ResourcesFaqRoute
  '/_resources/resources': typeof ResourcesResourcesRoute
  '/register/form': typeof RegisterFormRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/team'
    | '/about'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/register/form'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/team'
    | '/about'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/register/form'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_resources'
    | '/events'
    | '/team'
    | '/_resources/about'
    | '/_resources/contact'
    | '/_resources/faq'
    | '/_resources/resources'
    | '/register/form'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  EventsRoute: typeof EventsRoute
  TeamRoute: typeof TeamRoute
  RegisterFormRoute: typeof RegisterFormRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resources': {
      id: '/_resources'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resources/about': {
      id: '/_resources/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ResourcesAboutRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/_resources/contact': {
      id: '/_resources/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ResourcesContactRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/_resources/faq': {
      id: '/_resources/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof ResourcesFaqRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/_resources/resources': {
      id: '/_resources/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesResourcesRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/form': {
      id: '/register/form'
      path: '/register/form'
      fullPath: '/register/form'
      preLoaderRoute: typeof RegisterFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesAboutRoute: typeof ResourcesAboutRoute
  ResourcesContactRoute: typeof ResourcesContactRoute
  ResourcesFaqRoute: typeof ResourcesFaqRoute
  ResourcesResourcesRoute: typeof ResourcesResourcesRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesAboutRoute: ResourcesAboutRoute,
  ResourcesContactRoute: ResourcesContactRoute,
  ResourcesFaqRoute: ResourcesFaqRoute,
  ResourcesResourcesRoute: ResourcesResourcesRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  EventsRoute: EventsRoute,
  TeamRoute: TeamRoute,
  RegisterFormRoute: RegisterFormRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
